### PR TITLE
feat: add ingress integration

### PR DESCRIPTION
**Pull request by amandahla**
Applicable spec: <link>

### Overview

This PRs add ingress integration to allow communication from Synapse to the IRC bridge.

Also:
- Fix how the registration file is generated since the -u parameter actually expects "to wherever your Matrix server can contact this IRC bridge."
https://matrix-org.github.io/matrix-appservice-irc/latest/bridge_setup.html#4-registration

### Rationale

Synapse needs to communicate with the Bridge.

### Library Changes

ingress

### Checklist

- [X] The [charm style guide](https://juju.is/docs/sdk/styleguide) was applied
- [X] The [contributing guide](https://github.com/canonical/is-charms-contributing-guide) was applied
- [X] The changes are compliant with [ISD054 - Managing Charm Complexity](https://discourse.charmhub.io/t/specification-isd014-managing-charm-complexity/11619)
- [X] The documentation is generated using `src-docs`
- [X] The documentation for charmhub is updated
- [X] The PR is tagged with appropriate label (`urgent`, `trivial`, `complex`)

### CODE REVIEW

**Review by nrobinaubertin — DISMISSED** [review]

**Review by jdkandersson — COMMENTED** [review]
Looks good, Javi should be back next week for the senior review

**Comment by amandahla** [comment]
Related
https://github.com/canonical/haproxy-operator/pull/45

**Comment by javierdelapuente** [comment]
Looks good to me, but tests are failing

**Review by javierdelapuente — DISMISSED** [review]

**Review by javierdelapuente — APPROVED** [review]

**Comment by weiiwang01** [comment]
The `ingress` charm library and many `ingress` integration providers make a lot of assumptions that everything is deployed on Kubernetes. Since the `irc-bridge` charm is a machine charm, I’m not sure if this will work in practice. The `nginx-ingress-integrator` might be a slightly better because the machine-Kubernetes scenario was considered during its implementation, though it was never tested in such a setup so I am not sure if that's gonna work.

**Comment by gregory-schiano** [comment]
> The `ingress` charm library and many `ingress` integration providers make a lot of assumptions that everything is deployed on Kubernetes. Since the `irc-bridge` charm is a machine charm, I’m not sure if this will work in practice. The `nginx-ingress-integrator` might be a slightly better because the machine-Kubernetes scenario was considered during its implementation, though it was never tested in such a setup so I am not sure if that's gonna work.

We've been developing the HAProxy machine charm using the Ingress library and didn't face any issues. What are the assumptions that the `ingress` library takes concerning Kubernetes ? Because I didn't find any.

**Review by gregory-schiano — APPROVED** [review]

**Comment by weiiwang01** [comment]
> > The `ingress` charm library and many `ingress` integration providers make a lot of assumptions that everything is deployed on Kubernetes. Since the `irc-bridge` charm is a machine charm, I’m not sure if this will work in practice. The `nginx-ingress-integrator` might be a slightly better because the machine-Kubernetes scenario was considered during its implementation, though it was never tested in such a setup so I am not sure if that's gonna work.
> 
> We've been developing the HAProxy machine charm using the Ingress library and didn't face any issues. What are the assumptions that the `ingress` library takes concerning Kubernetes ? Because I didn't find any.

The ingress charm I have in mind is the traefik-k8s charm, which only uses the `host` in the ingress integration for service endpoints. However, on machine charms, the `host` is not resolvable, which causes problems.

**Pull request merged**
